alias ls='ls -1 --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -1A --color=auto'
alias lla='ll -A'
alias rm='rm -i'
alias mkdir='mkdir -p'
alias df='df -h'

alias code='codium'
alias codehere='code . && exit'
alias poweroff='systemctl poweroff'
alias battery="cat /sys/class/power_supply/BAT1/capacity"
alias nano='nano -l -E -S'
alias py='python3'
alias gs='git status'
alias jasmin='java -jar ~/Documents/jasmin.jar'
