#!/bin/bash

# File bash essenziali
cp ~/.bashrc ~/progetti/dotfiles
cp ~/.bash_aliases ~/progetti/dotfiles

# Risorse X
cp ~/.Xresources ~/progetti/dotfiles

# Emacs
cp ~/.emacs ~/progetti/dotfiles
cp -r ~/.emacs.d ~/progetti/dotfiles

# Git configuration
cp -r ~/.gitconfig ~/progetti/dotfiles

# Script vari
cp -r ~/.scripts ~/progetti/dotfiles

# Nano
cp ~/.nanorc ~/progetti/dotfiles 

# .config
mkdir -p ~/progetti/dotfiles/.config

# i3wm
cp -r ~/.config/i3 ~/progetti/dotfiles/.config/

# Polybar
cp -r ~/.config/polybar ~/progetti/dotfiles/.config/

# Rofi
cp -r ~/.config/rofi ~/progetti/dotfiles/.config/ 

# Dunst
cp -r ~/.config/dunst ~/progetti/dotfiles/.config/

# Compton
cp ~/.config/compton.conf ~/progetti/dotfiles/.config/
