#!/bin/bash

bspc monitor -d 1 2 3

# Autostart applications
sxhkd &
feh --bg-fill $HOME/Pictures/wallpapers/red-and-black.jpg
bash $HOME/.scripts/launch.sh
xrdb -merge ~/.config/.Xresources
dunst &
bash $HOME/.scripts/check-updates
rm -f $HOME/*.png

# Config
bspc config border_width 5
bspc config window_gap 18

bspc config normal_border_color "#ff0033"
bspc config focused_border_color "#ff0033"

bspc rule kitty -a desktop=^2
