#!/bin/bash

bspc monitor -d 1 2 3

# Autostart applications
sxhkd &
xsetroot -cursor_name left_ptr
feh --bg-fill $HOME/Pictures/wallpapers/abstract1.png
bash $HOME/.scripts/start-polybar
xrdb -merge ~/.config/.Xresources
dunst &
bash $HOME/.scripts/check-updates
rm -f $HOME/*.png
xinput set-prop 11 "libinput Tapping Enabled" 1
compton &

# Config
bspc config border_width 0
bspc config window_gap 18

bspc rule kitty -a desktop=^2
