#!/bin/bash

border="#1F1F1F"
separator="#1F1F1F"
foreground="#A9ABB0"
background="#1F1F1F"
background_alt="#252525"
highlight_background="#af2ad4"
highlight_foreground="#FFFFFF"

# Launch Rofi
menu="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'App ' \
-hide-scrollbar true \
-bw 0 \
-lines 5 \
-line-padding 14 \
-padding 20 \
-width 15 \
-xoffset -800 -yoffset 120 \
-location 3 \
-columns 1 \
-show-icons -icon-theme "Papirus" \
-font "Fantasque Sans Mono 14" \
-color-enabled true \
-color-window "$background,$border,$separator" \
-color-normal "$background_alt,$foreground,$background_alt,$highlight_background,$highlight_foreground" \
<<< "Firefox|VS Code|GitHub|Discord|Nautilus|Telegram")"

case "$menu" in
  *Firefox) firefox &;;
  *VS\ Code) code &;;
  *GitHub) google-chrome-stable https://github.com &;;
  *Discord) discord &;;
  *Nautilus) nautilus &;;
  *Telegram) google-chrome-stable https://web.telegram.org &;;
esac
