#!/bin/bash

# Draw a rectangle using slop then read the geometry value
read -r X Y W H < <(slop -f "%x %y %w %h" -b 4 -t 0 -q)

[ -z "$X" ] && exit

bspc rule -r kitty
bspc rule -a kitty -o state=floating follow=on focus=on rectangle=${W}x${H}+${X}+${Y}

kitty

bspc rule -a kitty desktop='^1' follow=on focus=on state=tiled
