#!/bin/bash

shutdown=""
reboot=""
suspend=""
logout=""

options="$shutdown\n$reboot\n$suspend\n$logout"

chosen=$(echo -e "$options" | rofi -theme ~/.themes/powermenu.rasi -p "x" -dmenu)

case $chosen in
    $shutdown)
        bash ~/.scripts/poweroff-sure
        ;;
    $reboot)
        bash ~/.scripts/reboot-sure
        ;;
    $suspend)
        amixer set Master mute
        systemctl suspend
        ;;
    $logout)
        bspc quit 1
        ;;
esac
