#!/bin/bash

yes="Y"
no="N"

options="$yes\n$no"
chosen=$(echo -e "$options" | rofi -theme ~/.themes/sure.rasi -dmenu)

case $chosen in
    $yes)
        systemctl poweroff
        ;;
    $no)
        notify-send "Sistema" "Spegnimento annullato"
        ;;
esac
