#!/bin/bash

status=$(xinput list-props 11 | grep "Device Enabled" | xargs | cut -f4 -d" ")

if [ $status -eq 0 ];then
    xinput set-prop 11 "Device Enabled" 1
    notify-send "Sistema" "Touchpad attivato"
else
    xinput set-prop 11 "Device Enabled" 0
    notify-send "Sistema" "Touchpad disattivato"
fi
