#!/bin/bash

cp -r ~/.config/openbox ~/Documents/dotfiles/.config/
cp -r ~/.config/polybar ~/Documents/dotfiles/.config/
cp -r ~/.config/.Xresources ~/Documents/dotfiles/.config/.Xresources
cp -r ~/.config/kitty ~/Documents/dotfiles/.config/
cp -r ~/.config/compton.conf ~/Documents/dotfiles/.config/compton.conf
cp -r ~/.config/dunst ~/Documents/dotfiles/.config

cp -r ~/.config/i3/config ~/Documents/dotfiles/.config/i3/

cp -r ~/.scripts ~/Documents/dotfiles/
cp -r ~/.bash_aliases ~/Documents/dotfiles/.bash_aliases
cp -r ~/.bashrc ~/Documents/dotfiles/.bashrc
cp -r ~/.themes/test-theme ~/Documents/dotfiles/.themes
cp -r ~/.themes/rofi-theme.rasi ~/Documents/dotfiles/.themes/
cp -r ~/.fonts ~/Documents/dotfiles/
cp -r ~/.sounds ~/Documents/dotfiles/

cd ~/Documents/dotfiles
git add .
git commit -m "update"
git push
