#!/bin/bash

if [ $# -ne 1 ]
then
        echo "Uso errato"
        exit
fi

if [ $1 = "+" ]
then
        amixer set Master 5%+
elif [ $1 = "-" ]
then
        amixer set Master 5%-
fi

play $HOME/.sounds/drip.ogg &> /dev/null
